/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeArticle: typeof import('./components/HomeArticle/index.vue')['default']
    Indexx: typeof import('./components/Tooltip/indexx.vue')['default']
    MessageBox: typeof import('./components/MessageBox/MessageBox.vue')['default']
    RightSideItem: typeof import('./components/Sider/components/TopSider/right-side-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./components/Sider/side.vue')['default']
    SkeletonItem: typeof import('./components/SkeletonItem/skeleton-item.vue')['default']
    Timeline: typeof import('./components/Timeline/index.vue')['default']
    Tooltip: typeof import('./components/Tooltip/index.vue')['default']
    TopSider: typeof import('./components/Sider/components/TopSider/top-sider.vue')['default']
  }
}
