/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./src/components/breadcrumbs/index.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox/index.vue')['default']
    Notification: typeof import('./src/components/Notification/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/Tabs/index.vue')['default']
  }
}
