/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/personality/': RouteRecordInfo<'/personality/', '/personality', Record<never, never>, Record<never, never>>,
    '/system/login/Login': RouteRecordInfo<'/system/login/Login', '/system/login/Login', Record<never, never>, Record<never, never>>,
    '/system/login/LoginForm': RouteRecordInfo<'/system/login/LoginForm', '/system/login/LoginForm', Record<never, never>, Record<never, never>>,
    '/system/login/RegisterForm': RouteRecordInfo<'/system/login/RegisterForm', '/system/login/RegisterForm', Record<never, never>, Record<never, never>>,
  }
}
